export default {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    EDIT_CURRENT_USER_INFO: 'EDIT_CURRENT_USER_INFO',
    SET_CURRENT_PROFILE: 'SET_CURRENT_PROFILE',
    SET_CURRENT_USER_RECOMMEND: 'SET_CURRENT_USER_RECOMMEND'
}