export default {
	SET_USER_RECOMMENDS: 'SET_USER_RECOMMENDS',
	SET_DISCOVER_RECOMMENDS: 'SET_DISCOVER_RECOMMENDS',
	SET_RECOMMENDS: 'SET_RECOMMENDS',
	SET_CURRENT_RECOMMEND: 'SET_CURRENT_RECOMMEND'
}